name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - '🚀 feature'
  - title: '✨ enhancement'
    labels:
      - '✨ enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - '🐛 bug'
  - title: '🏗 Refactoring'
    labels:
      - '🏗 refactor'

include-labels:
  - '🚀 feature'
  - '✨ enhancement'
  - '🐛 bug'
  - '🏗 refactor'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # Add # and @ to disable mentions, and add ` to disable code blocks.

# We're not using the version resolver anymore since we're providing the version directly
# But keeping it as a fallback in case the version extraction fails
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - '🚀 feature'
      - '✨ enhancement'
  patch:
    labels:
      - '🐛 bug'
      - '🏗 refactor'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/ArgonFetch/ArgonFetch/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION