name-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - '🚀 feature'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
      - '✨ enhancement'
  - title: '🛠️ Refactors'
    labels:
      - 'refactor'
      - '🏗 refactor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - '🐛 bug'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

no-changes-template: 'No changes in this release.'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - '🚀 feature'
      - 'enhancement'
      - '✨ enhancement'
  patch:
    labels:
      - 'bug'
      - '🐛 bug'
      - 'refactor'
      - '🏗 refactor'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION