services:
  postgres:
    image: postgres:15
    container_name: argonfetch-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    restart: unless-stopped

  argonfetch:
    build:
      context: .
      dockerfile: src/ArgonFetch.API/Dockerfile
    container_name: argonfetch
    env_file: .env
    environment:
      ConnectionStrings__ArgonFetchDatabase: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "4358:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: