services:
  argonfetch-proxy:
    build:
      context: ./services/ArgonFetch.Proxy
      dockerfile: Dockerfile
    container_name: argonfetch-proxy
    restart: unless-stopped
    ports:
      - "4442:4442"