name: "Bug report"
description: "Report a bug"
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I checked for duplicate issues
          required: true
    validations:
      required: true

  - type: input
    id: affected_part
    attributes:
      label: What's broken?
      placeholder: "e.g., Spotify download"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Description
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: Error message (if any)
      placeholder: "Paste error here"
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional info
      placeholder: "Screenshots, logs, etc."