name: "Feature request"
description: "Suggest a new feature"
labels: ["enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I checked for duplicate requests
          required: true
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem
      placeholder: "What problem does this solve?"

  - type: textarea
    id: proposed_solution
    attributes:
      label: Solution
      placeholder: "What would you like to happen?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Any other solutions?"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional info
      placeholder: "Screenshots, mockups, etc."