/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CombinedStreamUrlDto { 
    bestQuality?: string | null;
    bestQualityDescription?: string | null;
    mediumQuality?: string | null;
    mediumQualityDescription?: string | null;
    worstQuality?: string | null;
    worstQualityDescription?: string | null;
}

