/**
 * ArgonFetch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreamReferenceDto } from './streamReferenceDto';
import { MediaRenditionDto } from './mediaRenditionDto';


/**
 * @type MediaInformationDtoVideo
 * @export
 */
export type MediaInformationDtoVideo = StreamReferenceDto;

