/**
 * ArgonFetch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlType } from './urlType';


export interface MediaRenditionDto { 
    key: string;
    label: string;
    description?: string | null;
    fileExtension: string;
    mimeType: string;
    urlType?: UrlType;
    fileSizeBytes?: any | null;
    height?: any | null;
    bitrate?: any | null;
    convertTo?: string | null;
}
export namespace MediaRenditionDto {
}


