/**
 * ArgonFetch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaInformationDtoVideo } from './mediaInformationDtoVideo';


export interface MediaInformationDto { 
    requestedUrl: string;
    video?: MediaInformationDtoVideo | null;
    audio?: MediaInformationDtoVideo | null;
    coverUrl?: string | null;
    title: string;
    author: string;
}

