/**
 * ArgonFetch.API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MediaType = 'Media' | 'PlayList' | 'Unknown';

export const MediaType = {
    Media: 'Media' as MediaType,
    PlayList: 'PlayList' as MediaType,
    Unknown: 'Unknown' as MediaType
};

