/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlType } from './urlType';


export interface MediaRenditionDto { 
    key: string | null;
    label: string | null;
    description?: string | null;
    fileExtension: string | null;
    mimeType: string | null;
    urlType?: UrlType;
    fileSizeBytes?: number | null;
    height?: number | null;
    bitrate?: number | null;
    convertTo?: string | null;
}
export namespace MediaRenditionDto {
}


