/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreamReferenceDto } from './streamReferenceDto';


export interface MediaInformationDto { 
    requestedUrl: string | null;
    video?: StreamReferenceDto;
    audio?: StreamReferenceDto;
    coverUrl: string | null;
    title: string | null;
    author: string | null;
}

