/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaRenditionDto } from './mediaRenditionDto';


export interface StreamReferenceDto { 
    renditions?: Array<MediaRenditionDto> | null;
}

