/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UrlType } from './urlType';


export interface StreamReferenceDto { 
    bestQualityDescription?: string | null;
    bestQualityKey?: string | null;
    bestQualityFileExtension?: string | null;
    bestQualityMimeType?: string | null;
    mediumQualityDescription?: string | null;
    mediumQualityKey?: string | null;
    mediumQualityFileExtension?: string | null;
    mediumQualityMimeType?: string | null;
    worstQualityDescription?: string | null;
    worstQualityKey?: string | null;
    worstQualityFileExtension?: string | null;
    worstQualityMimeType?: string | null;
    urlType?: UrlType;
}
export namespace StreamReferenceDto {
}


