/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StreamingUrlDto { 
    bestQualityDescription?: string | null;
    bestQuality?: string | null;
    bestQualityFileExtension?: string | null;
    mediumQualityDescription?: string | null;
    mediumQuality?: string | null;
    mediumQualityFileExtension?: string | null;
    worstQualityDescription?: string | null;
    worstQuality?: string | null;
    worstQualityFileExtension?: string | null;
}

