/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaRenditionDto } from './mediaRenditionDto';
import { UrlType } from './urlType';


export interface StreamReferenceDto { 
    urlType?: UrlType;
    renditions?: Array<MediaRenditionDto> | null;
}
export namespace StreamReferenceDto {
}


