/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UrlType = 0 | 1;

export const UrlType = {
    NUMBER_0: 0 as UrlType,
    NUMBER_1: 1 as UrlType
};

