/**
 * ArgonFetch.API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UrlType = 'Combined' | 'Media';

export const UrlType = {
    Combined: 'Combined' as UrlType,
    Media: 'Media' as UrlType
};

