using ArgonFetch.Application.Behaviors;
using ArgonFetch.Application.Queries;
using ArgonFetch.Application.Validators;
using FluentValidation;
using FluentValidation.AspNetCore;
using Mediator;
using Microsoft.OpenApi;
using Scalar.AspNetCore;
using System.Text.Json.Serialization;
using YoutubeDLSharp;

var builder = WebApplication.CreateBuilder(args);

if (File.Exists(".env"))
{
    foreach (var line in File.ReadAllLines(".env"))
    {
        var trimmedLine = line.Trim();
        if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
            continue;

        var parts = trimmedLine.Split('=', 2);
        if (parts.Length == 2)
        {
            Environment.SetEnvironmentVariable(parts[0], parts[1]);
        }
    }
}

#region Configure Services
builder.Services.AddControllers()
    .AddJsonOptions(o =>
        o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

// The same converter again, for the options the OpenAPI generator reads. It looks at
// Http.Json.JsonOptions while controllers serialise with the MVC ones, so configuring only the
// line above produced a document calling every enum an integer while the API sent their names.
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(o =>
    o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.Services.AddSpaStaticFiles(spaStaticFilesOptions => { spaStaticFilesOptions.RootPath = "wwwroot/browser"; });

builder.Services.AddMediator(options => options.ServiceLifetime = ServiceLifetime.Scoped);

builder.Services.AddMemoryCache();

builder.Services.AddSingleton<ArgonFetch.Application.Services.IToolPaths>(
    new ArgonFetch.Application.Services.ToolPaths(
        builder.Configuration["TOOLS_PATH"],
        builder.Configuration["COOKIES_PATH"]));
builder.Services.AddSingleton<ArgonFetch.Infrastructure.Services.MediaToolsService>();
builder.Services.AddHostedService(
    sp => sp.GetRequiredService<ArgonFetch.Infrastructure.Services.MediaToolsService>());

builder.Services.AddSingleton<ArgonFetch.Application.Services.IApplicationInfoService, ArgonFetch.Infrastructure.Services.ApplicationInfoService>();
#endregion

#region API Documentation
// The document is generated by the framework's own OpenAPI support. Pinned to 3.0 because the
// checked-in openapi.json and the generators that read it are 3.0 documents.
builder.Services.AddOpenApi(options =>
{
    options.OpenApiVersion = OpenApiSpecVersion.OpenApi3_0;

    options.AddDocumentTransformer((document, context, cancellationToken) =>
    {
        document.Info.Title = "ArgonFetch API";
        document.Info.Description = "Resolve a link to its downloadable media, and stream it.";

        return Task.CompletedTask;
    });
});
#endregion

#region External Services Configuration
builder.Services.AddScoped(sp =>
{
    var toolPaths = sp.GetRequiredService<ArgonFetch.Application.Services.IToolPaths>();

    return new YoutubeDL
    {
        YoutubeDLPath = toolPaths.YtDlpPath,
        FFmpegPath = toolPaths.FfmpegPath
    };
});

builder.Services.AddHttpClient();

builder.Services.AddHttpClient(
    ArgonFetch.Application.Services.MediaHttpClientDefaults.ClientName,
    client => client.DefaultRequestHeaders.UserAgent.ParseAdd(
        ArgonFetch.Application.Services.MediaHttpClientDefaults.UserAgent));
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ArgonFetch.Application.Interfaces.IFfmpegStreamingService, ArgonFetch.Infrastructure.Services.FfmpegStreamingService>();
builder.Services.AddScoped<ArgonFetch.Application.Interfaces.IAcceleratedDownloadService, ArgonFetch.Infrastructure.Services.AcceleratedDownloadService>();
builder.Services.AddScoped<ArgonFetch.Application.Services.ICombinedStreamUrlBuilder, ArgonFetch.Application.Services.CombinedStreamUrlBuilder>();
builder.Services.AddScoped<ArgonFetch.Application.Services.IProxyUrlBuilder, ArgonFetch.Application.Services.ProxyUrlBuilder>();
builder.Services.AddSingleton<ArgonFetch.Application.Services.IMediaUrlCacheService, ArgonFetch.Application.Services.MediaUrlCacheService>();
builder.Services.AddSingleton<ArgonFetch.Application.Services.IMediaHttpClients, ArgonFetch.Application.Services.MediaHttpClients>();

builder.Services.AddSingleton<ArgonFetch.Application.Services.IMaintenanceState, ArgonFetch.Application.Services.MaintenanceState>();
builder.Services.AddSingleton<ArgonFetch.Application.Services.IArchiveProgressTracker, ArgonFetch.Application.Services.ArchiveProgressTracker>();

// One proxy per line, rotated across fetches. No file means direct.
builder.Services.AddSingleton<ArgonFetch.Application.Services.IProxyPool>(sp =>
    new ArgonFetch.Application.Services.ProxyPool(
        ArgonFetch.Application.Services.ProxyPool.ReadList(builder.Configuration["PROXY_LIST_PATH"])));
#endregion

#region Validation
builder.Services.AddFluentValidationAutoValidation();
#region Plugins
var pluginOptions = builder.Configuration
    .GetSection(ArgonFetch.Application.Plugins.PluginOptions.SectionName)
    .Get<ArgonFetch.Application.Plugins.PluginOptions>() ?? new ArgonFetch.Application.Plugins.PluginOptions();

builder.Services.AddSingleton(pluginOptions);
builder.Services.AddSingleton<ArgonFetch.Application.Plugins.PluginInstaller>();
builder.Services.AddSingleton<ArgonFetch.Application.Plugins.PluginLoader>();
builder.Services.AddSingleton<ArgonFetch.Application.Plugins.IProviderContextFactory,
    ArgonFetch.Application.Plugins.ProviderContextFactory>();

builder.Services.AddSingleton<ArgonFetch.Application.Plugins.IProviderRegistry>(serviceProvider =>
{
    var loader = serviceProvider.GetRequiredService<ArgonFetch.Application.Plugins.PluginLoader>();
    var environment = serviceProvider.GetRequiredService<IWebHostEnvironment>();
    var root = Path.IsPathRooted(pluginOptions.Path)
        ? pluginOptions.Path
        : Path.Combine(environment.ContentRootPath, pluginOptions.Path);

    return new ArgonFetch.Application.Plugins.ProviderRegistry(
        loader.Load(root, pluginOptions.Install),
        serviceProvider.GetRequiredService<ILogger<ArgonFetch.Application.Plugins.ProviderRegistry>>());
});
#endregion

builder.Services.AddValidatorsFromAssemblyContaining<GetMediaQueryValidator>();
builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
#endregion

#region CORS Configuration
const string defaultCorsOrigin = "http://localhost:4200";

var allowedOrigins = Environment.GetEnvironmentVariable("CORS_ALLOWED_ORIGINS")?.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
    ?? new[] { defaultCorsOrigin }; // Default for development

var corsUsesDevelopmentDefault = allowedOrigins.Length == 1 && allowedOrigins[0] == defaultCorsOrigin;

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(corsBuilder =>
    {
        corsBuilder.WithOrigins(allowedOrigins);
        corsBuilder.WithExposedHeaders("Content-Disposition");
        corsBuilder.AllowAnyHeader();
        corsBuilder.AllowAnyMethod();
        corsBuilder.AllowCredentials();

        if (!builder.Environment.IsProduction())
        {
            corsBuilder.WithExposedHeaders("X-Impersonate");
        }
    });
});
#endregion

var app = builder.Build();

#region Startup Diagnostics
var startupLogger = app.Services.GetRequiredService<ILogger<Program>>();

{
    var pluginRoot = Path.IsPathRooted(pluginOptions.Path)
        ? pluginOptions.Path
        : Path.Combine(app.Environment.ContentRootPath, pluginOptions.Path);

    try
    {
        await app.Services.GetRequiredService<ArgonFetch.Application.Plugins.PluginInstaller>()
            .InstallAsync(pluginOptions, pluginRoot);

        var registry = app.Services.GetRequiredService<ArgonFetch.Application.Plugins.IProviderRegistry>();

        startupLogger.LogInformation("Plugins: {Count} loaded{Names}",
            registry.Plugins.Count,
            registry.Plugins.Count == 0 ? string.Empty : " - " + string.Join(", ", registry.Plugins.Select(p => $"{p.Id} {p.Version}")));
    }
    catch (Exception ex)
    {
        // Sources a plugin would have added stop working; everything yt-dlp handles still does.
        startupLogger.LogError(ex, "Plugins could not be prepared; continuing without them");
    }
}

if (app.Environment.IsProduction() && corsUsesDevelopmentDefault)
{
    startupLogger.LogWarning("CORS is using default localhost origin in production. Please set CORS_ALLOWED_ORIGINS environment variable.");
}

startupLogger.LogInformation("Proxy rotation: {Count} proxies loaded",
    app.Services.GetRequiredService<ArgonFetch.Application.Services.IProxyPool>().Count);
#endregion

#region Configure HTTP Pipeline
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.MapScalarApiReference();
}

app.UseStaticFiles();

if (!app.Environment.IsDevelopment())
{
    app.UseSpaStaticFiles();
}

app.UseRouting();
app.UseAuthorization();
app.UseCors();
app.MapControllers();

app.MapFallback("/api/{**path}", (HttpContext context) => Results.Problem(
    title: "Not Found",
    detail: $"No endpoint matches {context.Request.Path}.",
    statusCode: StatusCodes.Status404NotFound));
#endregion

#region SPA Configuration
if (!app.Environment.IsDevelopment())
{
    app.UseSpa(spa =>
    {
        spa.Options.SourcePath = "wwwroot";
    });
}
#endregion

app.Run();