name: Create Release Draft (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  create-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "Previous tag: $PREV_TAG"

      - name: Generate changelog
        id: changelog
        run: |
          VERSION="v${{ github.event.inputs.version }}"
          PREV_TAG="${{ steps.prev_tag.outputs.PREV_TAG }}"

          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "## What's Changed" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT

          if [ -z "$PREV_TAG" ]; then
            echo "### First Release 🎉" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s by @%an" --no-merges | head -20 >> $GITHUB_OUTPUT
          else
            # Get commits since last tag
            git log ${PREV_TAG}..HEAD --pretty=format:"- %s by @%an" --no-merges >> $GITHUB_OUTPUT
          fi

          echo "" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT

          if [ -n "$PREV_TAG" ]; then
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREV_TAG}...v$VERSION" >> $GITHUB_OUTPUT
          fi

          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release Draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: true
          prerelease: false