name: Docker Build Dev (Fast)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build-dev.yaml'
  pull_request:
    branches: [ main ]

jobs:
  build-fast:
    name: Fast Build (AMD64 only)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (AMD64 only for speed)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/ArgonFetch.API/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}:dev
          # Maximum caching
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository }}:dev
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BUILD_CONFIGURATION=Debug
          provenance: false
          sbom: false