name: Restrict Dev Issues

on:
  issues:
    types: [opened]

jobs:
  check-permission:
    runs-on: ubuntu-latest
    # Only run if it has the internal label OR has [DEV] in the title
    if: contains(github.event.issue.labels.*.name, 'internal') || contains(github.event.issue.title, '[DEV]')

    steps:
      - name: Check if user is maintainer
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.issue;
            const actor = context.actor;

            // Check if the user has write permission (maintainer/owner)
            try {
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: issue.owner,
                repo: issue.repo,
                username: actor
              });

              // If user doesn't have write/admin/maintain permission, close the issue
              if (!['write', 'admin', 'maintain'].includes(permission.permission)) {
                // Post comment explaining why
                await github.rest.issues.createComment({
                  owner: issue.owner,
                  repo: issue.repo,
                  issue_number: issue.number,
                  body: `Hi @${actor}! This issue template is restricted to repository maintainers only. Please use the bug report or feature request templates instead.`
                });

                // Close the issue
                await github.rest.issues.update({
                  owner: issue.owner,
                  repo: issue.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });

                // Remove the internal label
                await github.rest.issues.removeLabel({
                  owner: issue.owner,
                  repo: issue.repo,
                  issue_number: issue.number,
                  name: 'internal'
                });
              }
            } catch (error) {
              // If we can't check permissions (user not a collaborator), they're not a maintainer
              await github.rest.issues.createComment({
                owner: issue.owner,
                repo: issue.repo,
                issue_number: issue.number,
                body: `Hi @${actor}! This issue template is restricted to repository maintainers only. Please use the bug report or feature request templates instead.`
              });

              await github.rest.issues.update({
                owner: issue.owner,
                repo: issue.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }